<a href="https://colab.research.google.com/github/pimchayaW/MachineLeaning/blob/main/NumpyBeginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
d1_array = np.array([2.0,0.09,2.14,9.18,2.02,2.3,3.2,8.2])
print(d1_array)

[2.   0.09 2.14 9.18 2.02 2.3  3.2  8.2 ]


In [11]:
d2_array = np.array([[7,4],[2,5],[8,9]])
print(d2_array)
print(np.zeros)
print(np.ones)

[[7 4]
 [2 5]
 [8 9]]
<built-in function zeros>
<function ones at 0x7b01f96f6710>


In [13]:
sequence_int = np.arange(9,18)
print(sequence_int)

[ 9 10 11 12 13 14 15 16 17]


In [16]:
for n in range(1,6):
  random_int = np.random.randint(low=2,high=25,size=6)
  print(f"{n} : {random_int}")

1 : [14 20 15  3 20 14]
2 : [22 11 20 19 15 13]
3 : [10 15 23 24 16 19]
4 : [16 19  5  7 13 22]
5 : [24 21  4 10 22 18]


In [18]:
i = 0
while i<5:
  random_float = np.random.random(6) + i
  print(f"{i}:{random_float}")
  i=i+1

0:[0.46166917 0.1239597  0.55433746 0.26169176 0.83289586 0.38819402]
1:[1.68630519 1.41631626 1.26184597 1.88878622 1.8377345  1.50009332]
2:[2.50896021 2.56735755 2.11585127 2.77956506 2.66245669 2.06735139]
3:[3.20715535 3.66167613 3.72952799 3.62885938 3.94622792 3.00090189]
4:[4.37571642 4.83146568 4.76406387 4.08790374 4.59823583 4.2790021 ]


In [27]:
#create a linear dataset
feature = np.arange(6,21)
print(feature)
label = [(f*3)+4 for f in feature]
print(label)
#Add some noise to the dataset
n = 15
max, min = 2, -2
range_size = (max - min)
noise = np.random.rand(n) * range_size + min
print(noise)
i = 0
for i in range(len(label)):
  label[i] = label[i]+noise[i]
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64]
[ 1.17771454  1.0188427  -0.89383651  1.50312391 -1.60618678 -1.31619052
  1.11600117  1.53513217  0.6831485   1.78030395  1.71993474  0.44551607
  0.19191212 -1.60598382  1.14726444]
[23.177714541327312, 26.01884269560906, 27.106163485301018, 32.503123911668844, 32.39381322375739, 35.68380948091345, 41.11600116657466, 44.53513216810738, 46.68314849616492, 50.78030394502232, 53.71993474392215, 55.44551607051935, 58.19191211619212, 59.39401618418098, 65.14726443976244]


[-0.17250373 -0.83955247  1.6966925   0.28758252  0.48422556 -1.93259559
 -1.07804319  1.8156854   1.1217744   1.45434764 -1.287974    0.59398608
  1.56140366  1.44501767  1.34863224]
[62.21068670022635, 24.16044753134692, 29.696692496821036, 31.287582515268785, 34.48422555901841, 35.067404408060185, 38.92195680896842, 44.81568539513339, 47.12177440080894, 50.454347641389674, 50.712025997189855, 55.59398608328582, 59.561403658115665, 62.44501767113917, 65.34863224273845]
